[2024-10-25T23:20:26.300+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T23:20:26.323+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T23:20:26.337+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T23:20:26.337+0000] {taskinstance.py:2865} INFO - Starting attempt 13 of 18
[2024-10-25T23:20:26.355+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load> on 2024-10-23 00:00:00+00:00
[2024-10-25T23:20:26.361+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T23:20:26.367+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v02', 'load', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpu5tdi8gk']
[2024-10-25T23:20:26.369+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask load
[2024-10-25T23:20:26.371+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16720) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-25T23:20:26.372+0000] {standard_task_runner.py:72} INFO - Started process 16825 to run task
[2024-10-25T23:20:26.426+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [running]> on host d9df5aecafce
[2024-10-25T23:20:26.758+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v02' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T23:20:26.759+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T23:20:27.004+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-10-25T23:20:27.006+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T23:20:27.006+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-10-25T23:20:27.010+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T23:20:33.987+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T23:20:33.999+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T23:20:34.000+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_argentina_v02, task_id=load, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241025T232026, end_date=20241025T232034
[2024-10-25T23:20:34.037+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T23:20:34.059+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-25T23:20:34.060+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
