[2024-10-25T07:17:52.633+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T07:17:52.652+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v02.extract_and_land scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T07:17:52.662+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v02.extract_and_land scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T07:17:52.663+0000] {taskinstance.py:2865} INFO - Starting attempt 16 of 21
[2024-10-25T07:17:52.679+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_land> on 2024-10-23 00:00:00+00:00
[2024-10-25T07:17:52.684+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T07:17:52.687+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=91060) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-25T07:17:52.687+0000] {standard_task_runner.py:72} INFO - Started process 91162 to run task
[2024-10-25T07:17:52.688+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v02', 'extract_and_land', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp_02fx30v']
[2024-10-25T07:17:52.689+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask extract_and_land
[2024-10-25T07:17:52.740+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v02.extract_and_land scheduled__2024-10-23T00:00:00+00:00 [running]> on host 1ed3068e8402
[2024-10-25T07:17:52.782+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-10-25T07:17:52.783+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T07:17:52.784+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-10-25T07:17:52.787+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T07:17:53.044+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v02' AIRFLOW_CTX_TASK_ID='extract_and_land' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='16' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T07:17:53.045+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T07:17:57.673+0000] {logging_mixin.py:190} INFO - root
 |-- fecha: string (nullable = true)
 |-- valor: double (nullable = true)
[2024-10-25T07:17:57.674+0000] {logging_mixin.py:190} INFO - root
 |-- fecha: string (nullable = true)
 |-- valor: double (nullable = true)
[2024-10-25T07:17:57.676+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T07:17:57.688+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T07:17:57.689+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_argentina_v02, task_id=extract_and_land, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241025T071752, end_date=20241025T071757
[2024-10-25T07:17:57.745+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T07:17:57.783+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-25T07:17:57.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
