[2024-10-25T08:20:35.694+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T08:20:35.713+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T08:20:35.723+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T08:20:35.723+0000] {taskinstance.py:2865} INFO - Starting attempt 20 of 23
[2024-10-25T08:20:35.739+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-23 00:00:00+00:00
[2024-10-25T08:20:35.744+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:20:35.748+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v02', 'transform', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbajwgmhb']
[2024-10-25T08:20:35.750+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask transform
[2024-10-25T08:20:35.752+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15912) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-25T08:20:35.753+0000] {standard_task_runner.py:72} INFO - Started process 16014 to run task
[2024-10-25T08:20:35.800+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [running]> on host d9df5aecafce
[2024-10-25T08:20:36.019+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v02' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='20' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T08:20:36.019+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T08:20:46.364+0000] {logging_mixin.py:190} INFO - +----------+-------------+-------------+
|     fecha|valor_mensual|valor_mensual|
+----------+-------------+-------------+
|2018-07-31|          3.1|         31.2|
|2018-08-31|          3.9|         34.4|
|2018-09-30|          6.5|         40.5|
|2018-10-31|          5.4|         45.9|
|2018-11-30|          3.2|         48.5|
|2018-12-31|          2.6|         47.6|
|2019-01-31|          2.9|         49.3|
|2019-02-28|          3.8|         51.3|
|2019-03-31|          4.7|         54.7|
|2019-04-30|          3.4|         55.8|
|2019-05-31|          3.1|         57.3|
|2019-06-30|          2.7|         55.8|
|2019-07-31|          2.2|         54.4|
|2019-08-31|          4.0|         54.5|
|2019-09-30|          5.9|         53.5|
|2019-10-31|          3.3|         50.5|
|2019-11-30|          4.3|         52.1|
|2019-12-31|          3.7|         53.8|
|2020-01-31|          2.3|         52.9|
|2020-02-29|          2.0|         50.3|
+----------+-------------+-------------+
only showing top 20 rows
[2024-10-25T08:20:47.376+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag.py", line 67, in transform
    df_joined.write.csv(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1864, in csv
    self._jwrite.csv(path)
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `valor_mensual` already exists. Consider to choose another name or rename the existing column.
[2024-10-25T08:20:47.438+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=indices_argentina_v02, task_id=transform, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241025T082035, end_date=20241025T082047
[2024-10-25T08:20:47.492+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T08:20:47.493+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 119 for task transform ([COLUMN_ALREADY_EXISTS] The column `valor_mensual` already exists. Consider to choose another name or rename the existing column.; 16014)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag.py", line 67, in transform
    df_joined.write.csv(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1864, in csv
    self._jwrite.csv(path)
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `valor_mensual` already exists. Consider to choose another name or rename the existing column.
[2024-10-25T08:20:47.559+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-25T08:20:47.586+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-25T08:20:47.588+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
